// <auto-generated />
using System;
using Library_Management_API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library_Management_API.PL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250104165007_initial")]
    partial class initial
    {
    }
}
